#! /bin/bash
#SBATCH -J predict
#SBATCH -D /scratch/shulinhe/phylogeny/ProteinPredict
#SBATCH -o predict.%j.out
#SBATCH --nodes=1-1
#SBATCH --ntasks=6
#SBATCH --mem=5000
#SBATCH --time=5:00:00
#SBATCH --mail-type=all
#SBATCH --mail-user=shulinhe@zedat.fu-berlin.de
for i in `cat files`; do TransDecoder.LongOrfs -t "$i".fasta -m 60; TransDecoder.Predict -t "$i".fasta; done
